export const demoAssets = [
  {
    _id: "asset-01",
    name: "Main Lobby Air Handler",
    qrId: "MIQ-HVAC-1001",
    category: "HVAC",
    location: { building: "North Tower", floor: "G", area: "Lobby" },
    model: "AHU-500",
    manufacturer: "Trane",
    installDate: "2023-04-12",
    warrantyExpiry: "2028-04-12",
    isCritical: true,
    status: "ACTIVE",
  },
  {
    _id: "asset-02",
    name: "Service Elevator B",
    qrId: "MIQ-ELV-2087",
    category: "Elevator",
    location: { building: "North Tower", floor: "All", area: "Core B" },
    model: "Gen2",
    manufacturer: "Otis",
    installDate: "2021-10-02",
    warrantyExpiry: "2026-10-02",
    isCritical: true,
    status: "UNDER_MAINTENANCE",
  },
  {
    _id: "asset-03",
    name: "Basement Pump Controller",
    qrId: "MIQ-PLM-3310",
    category: "Plumbing",
    location: { building: "South Annex", floor: "B1", area: "Pump Room" },
    model: "PX-42",
    manufacturer: "Grundfos",
    installDate: "2022-02-18",
    warrantyExpiry: "2027-02-18",
    isCritical: false,
    status: "ACTIVE",
  },
];

export const demoWorkOrders = [
  {
    _id: "wo-01",
    asset: demoAssets[0],
    reporterType: "PUBLIC",
    reportText: "Airflow is weak and there is a burning smell near the vent.",
    aiClassification: {
      category: "HVAC",
      priority: 5,
      summary: "Possible motor overheating or clogged filter.",
      suggestedCause: "Fan belt wear or blocked intake.",
    },
    status: "OPEN",
    assignedTechnician: null,
    createdAt: "2026-08-31T10:00:00.000Z",
  },
  {
    _id: "wo-02",
    asset: demoAssets[1],
    reporterType: "PUBLIC",
    reportText: "Elevator doors hesitate before closing on level 3.",
    aiClassification: {
      category: "Elevator",
      priority: 4,
      summary: "Door sensor needs inspection.",
      suggestedCause: "Dirty door track or sensor alignment drift.",
    },
    status: "IN_PROGRESS",
    assignedTechnician: { name: "Ayesha Khan" },
    createdAt: "2026-08-29T12:30:00.000Z",
  },
  {
    _id: "wo-03",
    asset: demoAssets[2],
    reporterType: "PUBLIC",
    reportText: "Pump controller alarm is blinking intermittently.",
    aiClassification: {
      category: "Plumbing",
      priority: 3,
      summary: "Intermittent electrical fault reported.",
      suggestedCause: "Loose relay or moisture in panel.",
    },
    status: "ASSIGNED",
    assignedTechnician: { name: "Bilal Ahmed" },
    createdAt: "2026-08-28T09:15:00.000Z",
  },
];
